- hosts: testing
  become: true
  tasks:
  - yum:
      name: 
      - docker
      state: present
  - name: Start Docker service
    service:
      name: docker
      state: started
  - name: Pull docker image
    community.docker.docker_image:
      name: maxshen01/movies-db:latest
      source: pull
  - name: Copy docker-compose.yml 
    copy:
      src: ../../docker-compose.yml
      dest: /root/docker-compose.yml
  - name: Start containers
    community.docker.docker_compose:
      project_src: /root
      state: present
